### ISSUE TITLE
MT5 EndOfStreamException

### ISSUE THREAD

**Issue by philyeahz** [philyeahz/ShenmueDKSharp#3]
In the MT5Mesh constructor there is an EndOfStreamException for some files.

Files:
- GACK6HKG.MT5
- GACK6TSG.MT5
- GACK6TZG.MT5
- GACK6XKG.MT5
- GACRDR1G.MT5
- GACRDR2G.MT5
- GACRGBIG.MT5
- GACRMETG.MT5
- SPBK6BRG.MT5
- SPBK6REG.MT5
- SPBK6YEG.MT5

**Comment by derplayer** [comment]
* SCENE\01\OP00\_OP99.AFS_\_file_3.PKS_\BMWS703G.CHRM

**Comment by philyeahz** [comment]
Fixed.
